//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page__Layout_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Shared\_Layout.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Shared\_Layout.cshtml"
           __o = Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" });


#line default
#line hidden

#line 5 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Shared\_Layo                      Partiall._LoginPartialndex", "Home");


#line default
#line hidden

#line 6 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Shared\_Layo   
     RenderBodyHoginPartial")Html.ActionLink")<

#line default
#line hidden

#line 7 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Vi                 \ShareDateTime.Now.YearRenderBody()          __o = Html.ActionLink("Contact", "Contact", "Home");


#line default
#line hidden

#line 8 "C:\Users\opilane\AppData\Local\Temp\77      ScriptsDRender("~/bundles/jquery")imeENow.Yearayout.cshtml"
           __o = Html.Partial("_LoginPartial");


#line default
#line hidden

#line 9 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE447F7AAScripts.Renderbootstrapndles/jquery"2E\4\trahv\Views\Shared\_Layout.cshtml"
   __o = RenderBody();


#line default
#line hidden

#line 10 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Shared\_Layout.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Optimization;
using System.Web.Routing;
using trahv;

public class _Page_Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
private static object @__o;
#line hidden
public _Page_Views_Shared__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
      __o = ;


#line default
#line hidden

#line 2 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
__o = ;


#line default
#line hidden

#line 3 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
__o = ;


#line default
#line hidden

#line 4 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
           __o = ;


#line default
#line hidden

#line 5 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
                   __o = ;


#line default
#line hidden

#line 6 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
                   __o = ;


#line default
#line hidden

#line 7 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
                   __o = ;


#line default
#line hidden

#line 8 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
           __o = ;


#line default
#line hidden

#line 9 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
   __o = ;


#line default
#line hidden

#line 10 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
                 __o = ;


#line default
#line hidden

#line 11 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
__o = ;


#line default
#line hidden

#line 12 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
__o = ;


#line default
#line hidden

#line 13 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
__o = ;


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Optimization;
using System.Web.Routing;
using trahv;

public class _Page_Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
private static object @__o;
#line hidden
public _Page_Views_Shared__Layout_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
      __o = ViewBag.Title;


#line default
#line hidden

#line 2 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
__o = Styles.Render("~/Content/css");


#line default
#line hidden

#line 3 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/modernizr");


#line default
#line hidden

#line 4 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
           __o = Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" });


#line default
#line hidden

#line 5 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
                   __o = Html.ActionLink("Home", "Index", "Home");


#line default
#line hidden

#line 6 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
                   __o = Html.ActionLink("About", "About", "Home");


#line default
#line hidden

#line 7 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
                   __o = Html.ActionLink("Contact", "Contact", "Home");


#line default
#line hidden

#line 8 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
           __o = Html.Partial("_LoginPartial");


#line default
#line hidden

#line 9 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
   __o = RenderBody();


#line default
#line hidden

#line 10 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
                 __o = DateTime.Now.Year;


#line default
#line hidden

#line 11 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/jquery");


#line default
#line hidden

#line 12 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
__o = Scripts.Render("~/bundles/bootstrap");


#line default
#line hidden

#line 13 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\2\trahv\Views\Shared\_Layout.cshtml"
__o = RenderSection("scripts", required: false);


#line default
#line hidden
}
}
}
