//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

#line 1 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
using trahv.Models;

#line default
#line hidden

public class _Page_Login_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Login_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 2 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
__o = model;


#line default
#line hidden

#line 3 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
  
    ViewBag.Title = "Log in";


#line default
#line hidden

#line 4 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
__o = ViewBag.Title;


#line default
#line hidden

#line 5 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
            using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                

#line default
#line hidden

#line 6 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
           __o = Html.AntiForgeryToken();


#line default
#line hidden

#line 7 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
                                        
                

#line default
#line hidden

#line 8 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
                                                       
                

#line default
#line hidden

#line 9 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
                      
                

#line default
#line hidden

#line 10 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
           __o = Html.ValidationSummary(true, "", new { @class = "text-danger" });


#line default
#line hidden

#line 11 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
                                                                                 
                

#line default
#line hidden

#line 12 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
               __o = Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" });


#line default
#line hidden

#line 13 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
                   __o = Html.TextBoxFor(m => m.Email, new { @class = "form-control" });


#line default
#line hidden

#line 14 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
                   __o = Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" });


#line default
#line hidden

#line 15 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
                      
                

#line default
#line hidden

#line 16 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
               __o = Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" });


#line default
#line hidden

#line 17 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
                   __o = Html.PasswordFor(m => m.Password, new { @class = "form-control" });


#line default
#line hidden

#line 18 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
                   __o = Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" });


#line default
#line hidden

#line 19 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
                      
                

#line default
#line hidden

#line 20 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
                       __o = Html.CheckBoxFor(m => m.RememberMe);


#line default
#line hidden

#line 21 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
                       __o = Html.LabelFor(m => m.RememberMe);


#line default
#line hidden

#line 22 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
                      
                

#line default
#line hidden

#line 23 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
                      
                

#line default
#line hidden

#line 24 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
               __o = Html.ActionLink("Register as a new user", "Register");


#line default
#line hidden

#line 25 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
                    
                

#line default
#line hidden

#line 26 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
                         
            }

#line default
#line hidden

#line 27 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
       __o = Html.Partial("_ExternalLoginsListPartial", new ExternalLoginListViewModel { ReturnUrl = ViewBag.ReturnUrl });


#line default
#line hidden
DefineSection("Scripts", () => {


#line 28 "C:\Users\opilane\AppData\Local\Temp\775FBBAE65AFE4A7C47F7AA4BF8DFAAA102E\4\trahv\Views\Account\Login.cshtml"
__o = Scripts.Render("~/bundles/jqueryval");


#line default
#line hidden
});

}
}
}
